# Use the official Node.js image as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY frontend/package*.json ./

# Install the frontend dependencies
RUN npm install

# Copy the frontend source code into the container
COPY frontend/ ./

# Build the frontend app
RUN npm run build-frontend

# Install a lightweight HTTP server (like serve) to serve the built app
RUN npm install -g serve

# Expose the port the frontend app will run on
EXPOSE 5000

# Serve the app
CMD ["serve", "-s", "dist", "-l", "5000"]
